### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by ayushnawal**

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed. I see those `pyc` cache files pushed. Please remove them.

This repository does not contain a `.gitignore` file. Please see #4  as an opportunity.

Interesting to see no other change except the `exec` command.

Also update your commit message to something meaningful, simply `porting` does not imply that you are "Porting to Python 3" :-)

**Comment by Aniket21mathur** [comment]
Tested. The Python 3 change seems to work.

**Comment by ayushnawal** [comment]
Thanks for the review @Aniket21mathur .
I was unable to remove those pyc files so i made the same changes in a new branch after adding the gitignore file and made a new [PR ](https://github.com/sugarlabs/calendario/pull/9).
I have tested the activity again.
You can merge that PR and I will close this PR.

**Comment by quozl** [comment]
In future please keep the same pull request open.  There was no need to start a new one.  All you had to do was "git rm *.pyc" then "git commit" then "git push".

**Pull request closed without merging**
