### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by ayushnawal**
Updated Readme file as suggested in this [review](https://github.com/sugarlabs/calendario/issues/7).

@quozl please review. Thanks :)

### CODE REVIEW

**Comment by quozl** [comment]
Valuable information in README is being deleted.  Please don't.

**Comment by ayushnawal** [comment]
I was unable to understand the language, so I preferred creating a new file.

**Comment by quozl** [comment]
Google Translate explains it well;

> Activity Calendar for Sugar
> Original developer
> -Yader Velásquez <yaderv@fedoraproject.org>
> INSTALL
> yum install sugar-calendar

Now do you understand?

**Comment by quozl** [comment]
Sorry, looks like situation has changed.  Fedora has declared the package dead, so you can remove the part about installing using `yum` now.

https://src.fedoraproject.org/rpms/sugar-calendario

Looks like the porting to Python 3 was too late to keep it in Fedora.

**Pull request merged**
